### ISSUE TITLE
Support configuration of the "id" key name

### ISSUE THREAD

**Issue by gmac** [movio/bramble#109]
The fact that Bramble hard-codes the federation key name as `id` is prohibitively strict; and it should be pretty simple to make that configurable. This would unlock Bramble for graphs that don't call their primary key `id`.

Interesting backstory – I actually worked on such a graph. In its early days as a collection of decoupled services, each type in each service had implemented its own unique `id` signature – sometimes as `Int`, sometimes as `String`, sometimes as `ID`. Once our federation intentions were solidified, it was already too late to standardize on one `id` field format because so much was built around the existing type-specific IDs. Thus, a new field called `uid` (unique id) was introduced across the graph as the federation key. It would be a shame not to support such a graph simply due to its history around the name "id".

**Comment by nmaquet** [comment]
@gmac What you're suggesting would be to make the federation key name configurable globally for the entire data graph, correct? Or were you thinking about a key name per object type?

**Comment by gmac** [comment]
While customizable keys per type are _useful_, I don't think they're strictly necessary here... Bramble isn't trying to win the customizability battle against the likes of Apollo Federation and Schema Stitching. However, it'd be a real bummer to have a graph of mutually-exclusive schemas keyed with a common field (a perfect fit for Bramble!) to be blocked simply because the common key name was something other than the string "id". Making it configurable once for the graph should be pretty simple.
