### ISSUE TITLE
Question: variables get inlined... where?

### ISSUE THREAD

**Issue by gmac** [movio/bramble#110]
@nmaquet @lucianjon @pkqk – I've been surprised to find very little code involving variables and arguments in the codebase. And yet, variables seem to work as expected – I can specify multiple query variables bound for different services, and Bramble seems to inline those values into their appropriate field arguments:

```graphql
query($_1: String!, $_2: String!) {
  svc1(input: $_1)
  svc2(input: $_2)
}
```

It appears that sub-service requests are never made with proper GraphQL variables – are gateway values always inlined into sub-queries? If so, where in the codebase does this happen? I've scoured all mentions of `Variables` and `Arguments`, but have found nothing that seems to perform this etherial transformation. Is this somehow being done by another package?

Thanks for the insight. This has really got me stumped.

**Comment by lucianjon** [comment]
@gmac I had to track this one down myself but it's happening in `formatSelectionSet` here https://github.com/movio/bramble/blob/main/query_execution.go#L100 and that will trace down to `expandAndFormatVariable`. Essentially all of the variables are stored inside the http context and then inlined last minute based on matching up the variable names.

**Comment by nmaquet** [comment]
@gmac variables are also used to evaluate `@skip` and `@include` directives here: https://github.com/movio/bramble/blob/9c7519545877e5e3cce79feb0f36adc93b8fd95b/execution.go#L155
(you can see how they're extracted from the context, too).

**Comment by gmac** [comment]
Whhhoooaa, I totally overlooked the significance of the formatting lib here. I kind of assumed that was just a “dumb” string utility and that all the primary logic would be happening as an AST transformation in the execution process. Thanks for the pointer, I see it now!

One related question on `@skip` and `@include`… I was surprised to see those included in the gateway. Technically, couldn’t those just get passed through to the underlying subservices to evaluate? I guess that could mess with null evaluation?

**Comment by nmaquet** [comment]
> One related question on @skip and @include… I was surprised to see those included in the gateway. Technically, couldn’t those just get passed through to the underlying subservices to evaluate? I guess that could mess with null evaluation?

It was relatively easy to implement so we added it in. I don't _think_ there is a downside to doing this? With very large documents, it may also be quite a bit more efficient, since pruning the selection set may result in calling fewer downstream services.

**Comment by gmac** [comment]
Makes sense. I can’t think of a downside either, I was just surprised to see them there.

**Comment by benzolium** [comment]
A year later I've probably found a downside of inlining. 🙂 

I'm trying to implement patch-like update mutation and distinguish between null fields and not send (undefined).
So on service side I'm looking into variables (selection set) and skip any of them if they are not present.

Is it possible to pass variables to downstream services? Or maybe there is another workaround?

**Comment by pkqk** [comment]
@benzolium we also found an issue with inlining variables recently with custom scalars and the difference between serialisation as JSON and GraphQL.

I think the answer will be to stop expanding and inline variables into the downstream service queries, and instead extract the relevant variables from the request payload, and pass them downstream.

**Comment by benzolium** [comment]
@pkqk could you please guide me how can I do it? Should I make a fork of bramble?

**Comment by pkqk** [comment]
@benzolium if you'd like to have a go at it then you can fork bramble and make a PR to this repo.

In [format.go](https://github.com/movio/bramble/blob/main/format.go#L88) it currently extracts the variables from the request context while formatting the queries for all the downstream services, and then inlines them into each query.

You'd need to alter `buildBoundaryQueryDocuments` and `executeBoundaryQuery` called in [execution.go](https://github.com/movio/bramble/blob/main/execution.go#L147) so instead it collects the variables used in each query and passes them along to the downstream services.
