### ISSUE TITLE
Custom HttpClient for queries to downstream services

### ISSUE THREAD

**Issue by jainpiyush19** [movio/bramble#121]
Currently there is no way to customize the underlying HTTPClient used by the `GraphQLClient`.

There are many different usecases where HTTPClient needs to be customzied like introducing circuit breakers or custom roundtrippers.

I would like to introduce a new option to set custom HTTPClient.

**Comment by pkqk** [comment]
Added to [v1.3.4](https://github.com/movio/bramble/releases/tag/v1.3.4)
