### ISSUE TITLE
Initial Docker pull does not run? (on macOS)

### ISSUE THREAD

**Issue by OscarAlmgren** [movio/bramble#15]
Very new to Go and GraphQL I wanted to check this out and play with it myself locally using the Docker image.

Ran into this from the initial docker command from the root of the git cloned repo. The directory contains the config.json file and `$(PWD)/config.json` resolves to the right path on tab completion. 

```❯ docker run -p 8082:8082 -p 8083:8083 -p 8084:8084 -v $(PWD)/config.json:/config.json ghcr.io/movio/bramble
Unable to find image 'ghcr.io/movio/bramble:latest' locally
latest: Pulling from movio/bramble`
60775238382e: Pull complete
621ff49b391a: Pull complete
Digest: sha256:c02a8d4977b6e2c49decbabdbba695ca702a44038554cbdde8cdeb1d64deb4a7
Status: Downloaded newer image for ghcr.io/movio/bramble:latest
standard_init_linux.go:219: exec user process caused: no such file or directory ```

**Comment by OscarAlmgren** [comment]
Also, noted now that on the initial git clone the config.json is listed as a directory..?

```
❯ ls -la config.*
-rw-r--r--  1 oscaralmgren  staff  7009 29 Mar 11:11 config.go

config.json:
total 0
drwxr-xr-x   2 oscaralmgren  staff    64 29 Mar 11:19 .
drwxr-xr-x  46 oscaralmgren  staff  1472 29 Mar 11:19 ..

**Comment by pkqk** [comment]
@OscarAlmgren the `config.json` being a directory possibly comes from a volume mount on a nonexistent file? There's no `config.json` in the repository. What `docker` command where you using to run the image?

#18 should address the image not executing
