### ISSUE TITLE
Request syntax error while trying to upload file

### ISSUE THREAD

**Issue by timspin** [movio/bramble#154]
Hi!

I've implemented file uploading using these library https://github.com/jaydenseric/graphql-multipart-request-spec for my graphql service. And it works correctly when I querying my service directly. But in case when there is bramble between I get error like:
`input:1: Syntax Error GraphQL request (1:36) Expected Name, found String`

So my question is: does bramble support those kind of queries with multipart/form-data content type?

**Comment by nmaquet** [comment]
Hi @timspin. This isn't something that we have used / found a need for yet but it does sound interesting. As you've noticed, Bramble doesn't currently support this but we would welcome any contributions.

**Comment by pkqk** [comment]
It looks like adding the [`MultipartForm`](https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/http_form.go) transport to [`gateway.go`](https://github.com/movio/bramble/blob/main/gateway.go#L39) will be needed

**Comment by benzolium** [comment]
It also looks like one will need to set `multipart/form-data` for downstream services [here](https://github.com/movio/bramble/blob/9a383e6d8ee90cd6f4708df8441e9972dc42e569/client.go#L109).

**Comment by benzolium** [comment]
@nmaquet @pkqk could you please guide me where to start implementing this feature?

I think I'd have to do something like [this in nautilus](https://github.com/nautilus/gateway/blob/deb7b43ac849154303d90835b349cb642981a3a0/http.go#L251), but in bramble.

**Comment by pkqk** [comment]
@benzolium the `github.com/99designs/gqlgen/graphql/handler` module should handle the receiving of multipart requests, I haven't tested it but I think the uploaded file streams will be available as variables.

You've identified the right spot in `client.go` where you'll need to add the option to make a multipart request to the downstream service in [your comment above](https://github.com/movio/bramble/issues/154#issuecomment-1473962456)

You could add something to the context that indicates if the incoming request used a multipart request, and then decide if based on the variables present (they are filtered down to only those necessary for the downstream request) if the downstream request needs to be a multipart request. (I wouldn't do it by default as it's not a standard transport and perhaps not all downstream services support it)

You might have to construct the multipart request yourself based on the spec, I haven't found a module that does it for you.

**Comment by gmac** [comment]
FWIW, I added this feature to Ruby stitching recently: https://github.com/gmac/graphql-stitching-ruby/pull/103. There’s some documentation and code there that may serve as a motivational example of the feature.
