### ISSUE TITLE
Micro integration

### ISSUE THREAD

**Issue by asim** [movio/bramble#16]
Super interesting stuff. I'm looking to find a way to integrate this into [micro](https://github.com/micro/micro). We have an API gateway that does http/json and path based resolution for grpc services but the api layer is always a pain. This looks pretty great.

**Comment by nmaquet** [comment]
Hey Asim, thanks for your comment. Looking forward to seeing what an integration with Micro would look like. The project and our docs are all still pretty new so let us know if anything needs clarification.

**Comment by nmaquet** [comment]
Closing this for now.
