### ISSUE TITLE
Lack of server timeouts

### ISSUE THREAD

**Issue by aerfio** [movio/bramble#161]
Http servers created in https://github.com/movio/bramble/blob/24b50dca339947b8e1424d9f70af15d3299a7284/main.go#L66-L69
don't have anything set in their "timeout" field which may lead to various problems. Zero value means no timeout

Links: 
- https://blog.cloudflare.com/exposing-go-on-the-internet/
- https://adam-p.ca/blog/2022/01/golang-http-server-timeouts/
- https://github.com/ory/graceful/blob/ecb4894ce882f348f659da531a47aaf99796d489/http_defaults.go#L51-L60 -> some library I personally like using, sets http.Server defaults to the same as in cloudflare blogpost

If you want I can prepare a PR which sets those defaults to 
```
	// DefaultReadTimeout sets the maximum time a client has to fully stream a request (5s)
	DefaultReadTimeout = 5 * time.Second
	// DefaultWriteTimeout sets the maximum amount of time a handler has to fully process a request (10s)
	DefaultWriteTimeout = 10 * time.Second
	// DefaultIdleTimeout sets the maximum amount of time a Keep-Alive connection can remain idle before
	// being recycled (120s)
	DefaultIdleTimeout = 120 * time.Second
```
but I'd like to first hear what do you think about it. Maybe some different values, maybe somehow expose it via configuration json?

**Comment by pkqk** [comment]
@aerfio good catch, we haven't hit any issues with the timeouts not being specified yet but that's probably luck more than anything.

An initial PR setting to recommended defaults would be appreciated, and if we do find a need to tweak them we can add the ability to configure them.
