### ISSUE TITLE
should bramble complain about built-in directives declared in spec?

### ISSUE THREAD

**Issue by benzolium** [movio/bramble#168]
I've recently encountered a bug when was trying to federate a service which contained `specifiedBy` directive. [It is in latest gql spec](https://spec.graphql.org/October2021/#sec--specifiedBy), but i've got an error:
```
Undefined directive specifiedBy.
``` 

Should I declare such directives in downstream services? Or it is a bug?

**Comment by pkqk** [comment]
Hi @benzolium we're using the [graphql-go](github.com/graph-gophers/graphql-go) library to parse GraphQL. I did a quick search of the library and can't find any support for the directive yet. We're at v1.3.0 but it looks like the v1.4.0 release also doesn't include it either.

As a quick fix you could declare the directive in your services, but is a bug that we're not supporting the new builtin directive.

**Comment by benzolium** [comment]
@pkqk thanks for the reply! I've opened an issue there.

Also thanks for a quick fix idea - I've just done that exact thing. 🙂

**Comment by benzolium** [comment]
@pkqk the package has been finally released.
But actually I can't write a test to reproduce the error. The only thing which was failing was vektah/gqlparser.

It was updated with specifiedby directive long time ago: https://github.com/vektah/gqlparser/releases/tag/v2.3.0.
Bramble is on 2.2.0 now so it's also worth updating.
