### ISSUE TITLE
Benchmarks comparison with Nautilus

### ISSUE THREAD

**Issue by prokaktus** [movio/bramble#20]
Hi!

This projects looks incredibly interesting! In our team we use Nautilus for federating our Graphql schemas. Bramble docs contains info about differences with Nautilus and it's super useful! What do you think about adding some performance benchmarks?

**Comment by nmaquet** [comment]
We would love to see some benchmarks of Bramble! We don't really have resources to tackle this now but we'd certainly link to benchmarks if somebody were to make some :)
