### ISSUE TITLE
Rate limiters on Bramble?

### ISSUE THREAD

**Issue by marcosuma** [movio/bramble#202]
I wonder if it's a good idea / advisable and if it's possible to implement a rate limiter at Bramble level.

Bramble works as a federation gateway and therefore an obvious solution is to have rate limiters on each of the graphql services. But I wonder if something has been thought on having rate limiters on the gateway.

**Comment by pkqk** [comment]
Hi @marcosuma, yes rate limiters would be a good idea at the gateway level. We haven't had the need for it yet, but I can see the use cases for it.

Like your other issue #203 it could probably be tested out as a plugin.
