### ISSUE TITLE
Strict-Transport-Security on Bramble?

### ISSUE THREAD

**Issue by marcosuma** [movio/bramble#203]
Is it possible to set the Strict-Transport-Security header from Bramble response?

**Comment by pkqk** [comment]
Hi @marcosuma,

You can modify the response by wrapping the public or private mux `http.Handler` using a plugin. There's a few examples in the [plugins](https://github.com/movio/bramble/tree/main/plugins) folder, the best one is probably the [cors](https://github.com/movio/bramble/blob/main/plugins/cors.go) example
