### ISSUE TITLE
Strict validation for enum types

### ISSUE THREAD

**Issue by chinmay1994** [movio/bramble#21]
First of all, thanks for making this! Our organisation is using apollo for schema stitching since a long time, and we were looking at alternatives to it. This looks really promising 😀. 

I was trying this out with one micro-service, and ran into this error:
```enum value isn't ALL_CAPS```

I understand that enum values _ideally_ should be all caps, but it is not strictly enforced by the graphql specification. Is this restriction really necessary ?

**Comment by chinmay1994** [comment]
I see a similar constraint for enforcing camel casing. https://github.com/movio/bramble/blob/3e52842f501f9855dbb99cfe6cc6af0a4b239b92/validate.go#L452

Could it be logged as a warning on startup, instead of completely restricting?

**Comment by Ackar** [comment]
Thanks for the suggestion @chinmay1994.
We've removed the checks, see https://github.com/movio/bramble/pull/24#issuecomment-813768146 for some background on this.

**Comment by chinmay1994** [comment]
Thanks for the quick response 👍
