### ISSUE TITLE
Subscriptions 

### ISSUE THREAD

**Issue by gedw99** [movio/bramble#22]
So the roadmap will or will not support subscriptions ?

so but I found the reasons to be ambiguously describing this

**Comment by nmaquet** [comment]
There are no current plans for implementing subscriptions as of yet, but we'd certainly welcome contributions from the community. The management of WebSockets and how holding on to them makes Bramble stateful is the main hurdle to overcome. We haven't really spent any time thinking about this too much yet.

**Comment by pkqk** [comment]
See #23 about keeping track of implementing/supporting subscriptions
