### ISSUE TITLE
Consider publising the container versions

### ISSUE THREAD

**Issue by zquintana** [movio/bramble#230]
Hello Bramble team,

I really like what you all have going here on this project. Recently while trying to deploy the service I realized it's not easily discernible what versions of the software are available in docker. It would be nice to be able to find that versions easily during implementation. I realize I could just not specify the version number, but that could mean that breaking changes could sneak into my production deployments.

**Comment by pkqk** [comment]
Hi @zquintana are you asking about the bramble image?

On every build we push an image to the GitHub Container Repository (ghcr.io) which is tagged with the version.

https://github.com/orgs/movio/packages/container/package/bramble

I haven't managed to get it to show up in the sidebar yet though.

**Comment by zquintana** [comment]
Yea, that's what I was referring to. I've gotten used to docker hub for finding image tags. I found a workaround though... `podman search ghcr.io/movio/bramble --list-tags`, if you're using `podman`.

**Comment by pkqk** [comment]
They are listed on the github packages site I posted above, it doesn't give you any details though other than the tag.

I'll see if I can associate them with the releases some time.
