### ISSUE TITLE
How to handle schema with field type graphql.DateTime 

### ISSUE THREAD

**Issue by cheku-bhutan** [movio/bramble#279]
Bramble is unable to handle  the service with schema containing field with type graphql.DateTime,

If anyone here has solution how to handle DateTime in Bramble, Please help me with sample code.

**Comment by pkqk** [comment]
Hi @cheku-bhutan what is the error you are getting? and what `graphql` module are you including?

Do you have
```graphql
scalar DateTime
```
in your schema? GraphQL doesn't have a DateTime type but if the schema defines a custom scalar then the parser treats it as a string and the graphql library you are using can map it to a type.
