### ISSUE TITLE
Add Fedaration gateway example

### ISSUE THREAD

**Issue by thangld322** [movio/bramble#48]
The document is lacking of examples. Can you add a simple working example of how to implement Federation gateway with @bramble? I can't manage to do it. Thank you!

**Comment by pkqk** [comment]
Hi @thangld322 

There are three example services in the [examples directory](/movio/bramble/tree/main/examples) if you run bramble with the `config.json` file set to point to those services
```json
{
  "services": [
    "http://nodejs-service:8080/graphql",
    "http://gqlgen-service:8080/graphql",
    "http://graph-gophers:8080/graphql"
  ]
}
```

Then you can request an arbitrary `Foo` object with any `id` value and each service will expose a field on the object.

```graphql
query {
  foo(id: "random") {
    nodejs
    gqlgen
    graphGophers
}
```

It's not a very detailed example but it does show the main features of the `@boundary` directive working.

I could put together a docker compose file that would run them all together if you would find that helpful to get the examples running?

**Comment by thangld322** [comment]
Thank @pkqk 
I'll try that out.
```
I could put together a docker compose file that would run them all together if you would find that helpful to get the examples running?
```
This would be very helpful!

**Comment by pkqk** [comment]
@thangld322 I haven't gotten a docker example yet but you can run the examples with these commands
```shell
cd examples/gqlgen-service
gqlgen generate
cd ../..
PORT=8092 go run ./examples/gqlgen-service/ &
PORT=8091 go run ./examples/graph-gophers-service/ &
BRAMBLE_SERVICE_LIST="http://localhost:8091/query http://localhost:8092/query" go run ./cmd/bramble
```

Then you can query to bramble at `http://localhost:8082/query` with:
```graphql
query {
  randomFoo {
    id
    gqlgen
    graphGophers
  }
}
```

**Comment by zlenderja** [comment]
@pkqk I get a long list of errors when I run `gqlgen generate`

```
validation failed: packages.Load: /Users/zlender/code/go/bramble/examples/gqlgen-service/generated.go:242:18: WithPathContext not declared by package graphql
/Users/user/code/go/bramble/examples/gqlgen-service/generated.go:242:47: NewPathWithField not declared by package graphql
/Users/user/code/go/bramble/examples/gqlgen-service/generated.go:257:18: WithPathContext not declared by package graphql
/Users/user/code/go/bramble/examples/gqlgen-service/generated.go:257:47: NewPathWithField not declared by package graphql
....
```

Any tips much appreciated.

**Comment by lucianjon** [comment]
Hi @zlenderja, that is likely due to a mismatch in version between the version of your installed `gqlgen` binary and the version bramble depends on. I'm working on a PR to update the deps but in the meantime I'd suggest running `cd examples/gqlgen-service && go generate`

**Comment by nzlov** [comment]
No foo(id:ID) is found after running the test demo
![image](https://user-images.githubusercontent.com/2859981/140001046-7ce14c94-f70b-493a-9bdd-ed7778d7da4f.png)
![image](https://user-images.githubusercontent.com/2859981/140000994-eb3b0883-1397-4892-8351-597dc3dbcd62.png)

**Comment by pkqk** [comment]
@nzlov this is correct, the fields with the `@boundary` directive are not exported in the final merged schema.

So in the demo the only field that returns a `Foo` is `randomFoo`, then bramble will ask each individual service for the fields it provides using the `foo(id: ID!)` resolvers.

**Comment by nzlov** [comment]
@pkqk thanks.

**Comment by suessflorian** [comment]
Hey @thangld322, not sure if this would be helpful;
> Can you add a simple working example of how to implement Federation gateway with @Bramble?

https://github.com/movio/bramble/pull/86/files
