### ISSUE TITLE
Optimize multiple @boundary fields lookup

### ISSUE THREAD

**Issue by pkqk** [movio/bramble#51]
Currently undocumented is the ability to use a `@boundary` resolver that looks up a list of objects instead of a single object, i.e.
```graphql
type Query {
  getFoos(ids: [ID!]!): [Foo!]! @boundary
}
```
instead of
```graphql
type Query {
  getFoo(id: ID!): Foo @boundary
}
```
However there are a few issues:
While there is some code that expects the list boundary lookup, the validator complains about the signature incorrectly. Seems like it also expects the return type signature to be `[Foo!]` instead of `[Foo!]!`.

In some cases it then fails to merge the fields onto the object from another service.

There are some example services on the [federation-id-deduplication](/movio/bramble/tree/federation-id-deduplication/examples) branch. `toomanyfoos` exposes some lookup fields to get a list of `Foo` objects. `zoot` adds some fields to the `Foo` object.

Run with:
```
PORT=8091 go run ./examples/toomanyfoos/ &
PORT=8092 go run ./examples/zoot/ &
BRAMBLE_SERVICE_LIST="http://localhost:8091/query http://localhost:8092/query" go run ./cmd/bramble
```

With the `foos` resolver present in `zoot` the query:
```graphql
query {
  toManyFoos {
    id
    bar
  }
}
```
returns
```json
{
  "errors": [
    {
      "message": "Cannot query field \"bar\" on type \"Foo\".",
      "locations": [
        {
          "line": 8,
          "column": 5
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ],
  "data": null
}
```
with the ID list resolver removed it returns the correct:
```json
{
  "data": {
    "toManyFoos": [
      {
        "id": "0",
        "bar": false
      },
      {
        "id": "1",
        "bar": false
      },
      {
        "id": "2",
        "bar": false
      },
      {
        "id": "3",
        "bar": false
      },
      {
        "id": "4",
        "bar": false
      },
      {
        "id": "5",
        "bar": false
      },
      {
        "id": "6",
        "bar": false
      },
      {
        "id": "7",
        "bar": false
      },
      {
        "id": "8",
        "bar": false
      },
      {
        "id": "9",
        "bar": false
      },
      {
        "id": "0",
        "bar": false
      },
      {
        "id": "1",
        "bar": false
      },
      {
        "id": "2",
        "bar": false
      },
      {
        "id": "3",
        "bar": false
      },
      {
        "id": "4",
        "bar": false
      },
      {
        "id": "5",
        "bar": false
      },
      {
        "id": "6",
        "bar": false
      },
      {
        "id": "7",
        "bar": false
      },
      {
        "id": "8",
        "bar": false
      },
      {
        "id": "9",
        "bar": false
      }
    ]
  }
}
```

Once this is working it would also be good if bramble could deduplicate the ids it looks up on the second service if the set is not unique, reducing the number of looks sent downstream. i.e. `TooManyFoos` returns a list of 20 items but there are only 10 unique items, this should cause either 10 `foo` lookups on `zoot` instead of 20, or a lookup of id ids on `foos` if the bulk boundary resolver is present.

**Comment by nmaquet** [comment]
This was fixed by https://github.com/movio/bramble/commit/d9902ccdf06df97ea92598f882228410557288ec
@gmac Good point I'll create a separate issue for this.
