### ISSUE TITLE
Use introspect instead of Service->schema 

### ISSUE THREAD

**Issue by berend** [movio/bramble#61]
Hi there,

we are currently considering using bramble. However, in the services we are combining, there is no Service endpoint yet and the schema is also generated and not so easy available as string (to make it available via the required Service Query).

We are wondering why the schema needs to be available via a query and is not retrieved via introspection. Is there any reason why that would not work?

We have used nautilus and afaik nautilus is doing exactly that.

Also, we are willing to contribute this as a feature - if nothing speaks against this. Just wanted to hear your opinions about this up front.

I am also on gophers slack as Berend Kapelle

**Comment by nmaquet** [comment]
Hey @berend, thanks for your question. Unfortunately, the reason Bramble cannot rely on introspection is that the GraphQL introspection API does not allow the client to ask for information about where directives are used and which arguments they received. See https://github.com/graphql/graphql-spec/issues/300 

Apollo Federation also relies on directives to annotate each federated service, for the same reason Bramble does. See https://www.apollographql.com/docs/federation/federation-spec/ (the `_Service.sdl` field in particular).

Nautilus doesn't use directives to annotate each schema, relying on a global `Node` interface instead. Bramble used to implement federation in this manner but the main drawback is that all federated entities must have globally unique IDs for this to work. This requires everyone to either use UUIDs or typename prefixes on all IDs which is quite a hassle. In the end, the current implementation feels like the appropriate tradeoff.

**Comment by berend** [comment]
Thanks for clarifying so quickly! Closing this one then.
