### ISSUE TITLE
getting GRAPHQL_VALIDATION_FAILED with the nodeJS example

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [movio/bramble#75]
Hello,
I'm having a hard time running the gateway, I did follow the below steps:
- did `npm install` and `npm start` on the node JS example and it's working fine in the browser and able to do the `fo` example query
- did run the gateway with the below config
```{
  "services": ["http://localhost:8080/graphql"],
  "gateway-port": 8082,
  "private-port": 8083,
  "metrics-port": 8084,
  "log-level": "info",
  "poll-interval": "5s",
  "max-requests-per-query": 50,
  "max-client-response-size": 1048576,
  "plugins": [

    {
      "name": "admin-ui"
    },
    {
      "name": "cors",
      "config": {
        "allowed-origins": ["*"],
        "allowed-headers": ["*"],
        "allow-credentials": true,
        "max-age": 3600,
        "debug": true
      }
    },
    {
      "name": "playground"
    }
  ]
}
```

but getting the below error in the gateway console 

```{"error":"error during request: Post \"http://localhost:8080/graphql\": read tcp [::1]:57847-\u003e[::1]:8080: read: connection reset by peer","level":"error","msg":"unable to update service","service":"nodejs-service","time":"2021-10-08T18:16:34.91806-05:00","url":"http://localhost:8080/graphql","version":"1.0.0"}```

also in the browser, it gives the below error 

![Screen Shot 2021-10-08 at 6 18 31 PM](https://user-images.githubusercontent.com/36244069/136633904-2fd921fa-8d94-47e7-bc53-a903163c8029.png)

appreciate your help

**Comment by nmaquet** [comment]
@ahmed-adly-khalil boundary fields aren't part of the  merged schema, they're used by Bramble internally to resolve federated query. That's why the `foo(id: 1) {id}` query fails with `GRAPHQL_VALIDATION_FAILED`: it's because `Query.foo` isn't part of the schema that Bramble exposes to the outside world. I hope this helps.
