### ISSUE TITLE
Broken boundary when aliasing id field

### ISSUE THREAD

**Issue by gmac** [movio/bramble#93]
## The Problem

Similar to https://github.com/movio/bramble/issues/90. There still appears to be sensitivity around `id` being aliased within the execution pipeline, even while running the reserved namespace safeguards in https://github.com/movio/bramble/pull/92. For example, this query still fails:

```graphql
query {
  shop1 {
    products {
      id: name
    }
  }
}
```

Here's the message:

```json
{
  "message": "got a null response for non-nullable field \"id\"",
  "path": [
    "shop1",
    "products",
    0,
    "id"
  ]
}
```

This issue is very specific to the `id` field, which suggests that [the special execution handling](https://github.com/movio/bramble/blob/main/query_execution.go#L523) of the `id` field causes the problem. Ideally, `id` should operate as a normal member of the GraphQL schema without restrictions.

## Proposed fix

The work in https://github.com/movio/bramble/pull/92 is a big step in the right direction here, however it leaves the [special execution rule](https://github.com/movio/bramble/blob/main/query_execution.go#L523) around `id` in place. To close this out once and for all, I'd suggest removing _all_ special considerations from the `id` field and to rely exclusively on the reserved `__id` namespace for federation mapping. With that, the complete schema will be an open book for standard GraphQL patterns, and only `__id` and `__typename` will impose restrictions about customizing their use.

**Comment by nmaquet** [comment]
Great spotting @gmac. I'll have a chat with @lucianjon on what would be the best way to address this.

**Comment by gmac** [comment]
The implementation of #90 in https://github.com/movio/bramble/pull/94 also fixes this. I’ll tidy up that PR later tonight and formally open it for consideration.
